---
apiVersion: v1
kind: Pod
metadata:
  name: echopod
spec:
  containers:
  - name: dater
    image: busybox
    command:
    - /bin/sh
    - "-c"
    - while true; do date; sleep 1; done
  - name: doomed
    image: busybox
    command:
    - /bin/sh
    - "-c"
    - for i in $(seq 1 5); do echo "$i"; sleep 1; done
